# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/conv_system/conv_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_system || ORIG_REF_NAME==conv_system} -quiet] -quiet

# IP: bd/conv_system/ip/conv_system_processing_system7_0_0/conv_system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_system_processing_system7_0_0 || ORIG_REF_NAME==conv_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/conv_system/ip/conv_system_axi_cdma_0_0/conv_system_axi_cdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_system_axi_cdma_0_0 || ORIG_REF_NAME==conv_system_axi_cdma_0_0} -quiet] -quiet

# IP: bd/conv_system/ip/conv_system_axi_bram_ctrl_0_0/conv_system_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_system_axi_bram_ctrl_0_0 || ORIG_REF_NAME==conv_system_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/conv_system/ip/conv_system_xbar_0/conv_system_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_system_xbar_0 || ORIG_REF_NAME==conv_system_xbar_0} -quiet] -quiet

# IP: bd/conv_system/ip/conv_system_auto_pc_0/conv_system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_system_auto_pc_0 || ORIG_REF_NAME==conv_system_auto_pc_0} -quiet] -quiet

# IP: bd/conv_system/ip/conv_system_ps7_0_axi_periph_0/conv_system_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_system_ps7_0_axi_periph_0 || ORIG_REF_NAME==conv_system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/conv_system/ip/conv_system_rst_ps7_0_100M_0/conv_system_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==conv_system_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/conv_system/ip/conv_system_axi_bram_ctrl_0_bram_0/conv_system_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_system_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==conv_system_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/conv_system/ip/conv_system_axi_smc_0/conv_system_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_system_axi_smc_0 || ORIG_REF_NAME==conv_system_axi_smc_0} -quiet] -quiet

# IP: bd/conv_system/ip/conv_system_axi_bram_ctrl_1_0/conv_system_axi_bram_ctrl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_system_axi_bram_ctrl_1_0 || ORIG_REF_NAME==conv_system_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/conv_system/ip/conv_system_axi_bram_ctrl_1_bram_0/conv_system_axi_bram_ctrl_1_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_system_axi_bram_ctrl_1_bram_0 || ORIG_REF_NAME==conv_system_axi_bram_ctrl_1_bram_0} -quiet] -quiet

# IP: bd/conv_system/ip/conv_system_conv_v1_0_0_0/conv_system_conv_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_system_conv_v1_0_0_0 || ORIG_REF_NAME==conv_system_conv_v1_0_0_0} -quiet] -quiet

# XDC: c:/Users/User/school/digi_sys_exp/DSProject_Final/3_System_Integration/conv_system/conv_system.gen/sources_1/bd/conv_system/conv_system_ooc.xdc
