# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/User/school/digi_sys_exp/DSProject_Final/3_System_Integration/conv_system/conv_system.srcs/sources_1/bd/conv_system/ip/conv_system_auto_pc_0/conv_system_auto_pc_0.xci
# IP: The module: 'conv_system_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/school/digi_sys_exp/DSProject_Final/3_System_Integration/conv_system/conv_system.gen/sources_1/bd/conv_system/ip/conv_system_auto_pc_0/conv_system_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'conv_system_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/User/school/digi_sys_exp/DSProject_Final/3_System_Integration/conv_system/conv_system.srcs/sources_1/bd/conv_system/ip/conv_system_auto_pc_0/conv_system_auto_pc_0.xci
# IP: The module: 'conv_system_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/school/digi_sys_exp/DSProject_Final/3_System_Integration/conv_system/conv_system.gen/sources_1/bd/conv_system/ip/conv_system_auto_pc_0/conv_system_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'conv_system_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
